apiVersion: v1
data:
  .dockerconfigjson: ENC[AES256_GCM,data:m5rJE8sbPe6wJmKNRTUud9BSAQ5dgEddNz/NghgyUaR00RfMthUTM9l4FHBr8DfFFVrv+UrfZs/K6HaRwkCnbyetrW84OXewLp7Rck8z5vFFmD28A2c+4gOZdzpsd3/4Q7nqcAamPWJtu9Axk5xjbB3KdFgeUhTkdzQ4vNz/DqphNGy66riyMNxTV597bDyBjTn5j4bl1G9JEGaUcrUa4WZ9uak5Jd7BznEfAAYDztUUlbjXjSCa3bH3Yt9OAjH0gJvbmabZA+Q1cjzSDfbf7CTIvZhDShYbtBSKox6jVuxEGDTJJyrZZTPgVEZxUWXr+EENLP0+5YhdLlbRCaD4RfwH0pCdh+uL0pzoxg==,iv:r3a9CYHRKihbBiJeehtahW+6wJi4XsHQ6QjrdfXXEBA=,tag:lzC3ThdQzVLgmAot+6qIsg==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: sake-hack-ns
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - recipient: age1lewhnmn5e7qf6wpm77eq55l272e6r7cxuq79mtwl24ad938vsarq8ta7ar
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnU2cyM2ZvTUJWUHoraHlP
        S2I3b0RHWlRGTy9RRTlvRmhVaWc0ODgwZTBRCkFJV2pNaUIwc1RNdUZaSHFLUjZG
        T2VPNy9hcEh6NkhsSzZYS1plRy9TN3MKLS0tIFduSGxKOWo2MWY3V3pyU1ExUHBF
        OFBaUGpkMmluK2hRMm83dnFEaER3ZDQKkbNurPEG2pHObNFd/Lm4aCBvUU5AnLlo
        LjY8gXCVcPautIAsyNiwjoPuCDQY9b2SB1whfwkFOrb93FG+nBiMoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T15:45:47Z"
  mac: ENC[AES256_GCM,data:wzMOWsgYfc+upAk3O1/bNtUYGt7rZFhnkt90qMRk6vzQV7uzY46wGW6kuenJQB/iqO2eWizgEGiPYpEGWhBReJj+qFPj4i8ETJ0XYjF4nIFo9IF9+pw6K/qxh9FJRw5wDA8fRSCf+Nirdz+go/fWEahPfgBMyW/HYgefMWoT8GU=,iv:1KbNCLjGdZ3/MQ+IH0YmmYvMMl1+T88m2nDQ/V52WQs=,tag:+x5n2Kr2dnbvi3Bp6HNJFA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
