apiVersion: v1
kind: Secret
metadata:
    name: sake-hack-backend-secrets
    namespace: sake-hack-ns
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:ujpoJlAgHmprInPYKwNrTfFWKVNfx61gglv37N16lnc=,iv:+NWUD40/Tk6oiNH6wLQQC9YtfoQPmSgxEMYvm7mLaB8=,tag:zbAUvh3Ka+rrD76/7/oeFQ==,type:str]
    CACHE_PASSWORD: ENC[AES256_GCM,data:XWGHDONkk8cHv2nMUbHU0c8GSw1ULWuk8c0j5sBjqU4=,iv:3zUU9lGSQIdFyZPc6QhOAwFYSr08/fkhUZ5kTNFLVwI=,tag:hDd1dXhFE3xhUOZ7s7iLlw==,type:str]
    JWT_SECRET: ""
    STORAGE_ACCESS_KEY: ENC[AES256_GCM,data:IRRyjeR+pU2cTjwcs97+VsiFZWw=,iv:+KSQJQSVzzeg+FnsdggHvCu2dBi4Ll9YuRNsDjkDomI=,tag:3J2KQpcz8NPhLHJzN5eMOQ==,type:str]
    STORAGE_SECRET_KEY: ENC[AES256_GCM,data:B9Gyco5GmSh4nDoqTBd5x9V8DZNNKeH7GfJDYOzHReTc1lpfkHcLlA==,iv:a19XtSxDAPJajzQIuq/biz9RqPM/CNqp0lUNymRJKKg=,tag:4trySiodUySYXYg6oWdObg==,type:str]
sops:
    age:
        - recipient: age1lewhnmn5e7qf6wpm77eq55l272e6r7cxuq79mtwl24ad938vsarq8ta7ar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OFMvdUlQRHJMSjhRSHIv
            WUl0QlRWSE9QcjkzT0F0RVNZaStXOU92dkZrCk9JdmJpTkNISTg0TFp4Uk5VNVU3
            cEVTSFlJWG5Famg5NXlsS1BQN2UyeUUKLS0tIHpPdEdlNi8yeExRT2lMTW13U0pv
            MDVYRldBNEN3RmtaY2M1aDV6Ymo2STAKd7zcz8odMA+SO85XTOqXro5Q/FZQrRDX
            qqlOfIeZeOA0ZW3RpB3uXn2iBfSE7Sl3jLWsZ6eGUH2OMel8B8+w6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T14:43:07Z"
    mac: ENC[AES256_GCM,data:enPLikJ7ZV552vJD+/zce+o9FOWdqBJvkxm0rEtCFbua/6dqPKcowDpm4iJZFzzCelA3epNw6xZ1KGbTFcfGVKLThalojO0ejolU9GHxhYccdJOMeuLqdr9F/7BEdcCc7pCHV8QXReAFn2vDVbNOu5QywjmazqTpaK0xKqztCAU=,iv:NuKuATaT17URAl+YpWFjeguKU4FPqJHgXiZNuXJHO64=,tag:7rTYACXTgr95zMZJ/tQUHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
