apiVersion: v1
kind: Secret
metadata:
    name: sake-hack-backend-secrets
    namespace: sake-hack-ns
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:lMwm4Kdy2Ra03h6qGRrQVlYnG62eDRw6+Oi5BRGDRX4=,iv:F6rWGcRiCxj1/a9tA4xrq6bhwtePF6P43CMt1U26+K4=,tag:39CB1ca5+Fx/cn2h/HDGYg==,type:str]
    CACHE_PASSWORD: ENC[AES256_GCM,data:DO3VVdQhBeAn0BkbgXE/Vz9ZSmmP5DIVFERASOG3PxE=,iv:1M3S8pWoqP1kE6T/saTBSbAs+qkOosQC0bEgv5MIgUU=,tag:KRhehUILFwwg95I0mEkCRA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:uGwhVlDlGovjWsxIVp0C6wCRge1ghbtBJqCB5de5w4choBEqgZKzmhCatGdYc5ooLE18VBlrma5vlX7dm2ftOg==,iv:w5LD4eGfxnwcJy5fpWxuIfLesPsD5krDHrczOuJNtds=,tag:c9SdJiJtprLhlMT5o7j3hQ==,type:str]
    STORAGE_ACCESS_KEY: ENC[AES256_GCM,data:FKCmqZkn/n7Fid0DCgDeViEvVKs=,iv:iOrbZcTVB6Gkv4n5AEk2CFrjbgS+367q7eoj8nENnUM=,tag:VLnmOzcTbcjJ9ogv+CV9vg==,type:str]
    STORAGE_SECRET_KEY: ENC[AES256_GCM,data:xMWSC/iX4WpFeV42s4G+KLkYQ0OPwVVG4NPrGo11q0+4ioyBTxKNVQ==,iv:eAYRn5XwqEe6eV/de8xXE4PDaegIpqZQQ2RfVeEqZOQ=,tag:c9jOsADxM5KFTTM1wu+AhQ==,type:str]
sops:
    age:
        - recipient: age1lewhnmn5e7qf6wpm77eq55l272e6r7cxuq79mtwl24ad938vsarq8ta7ar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMTNkWnRuOVR4OHdVZWFL
            RGtiK0hWeU93b2lmRWhLV0ZHQjBIaUhKMVRnCi9oUjVXMFQ5SkpCeWNlT2wrcERR
            d3QvWXdtWVRsYjFWV05laUI3b3pVS0kKLS0tIEI1RjkzTnIzaHFCd0hlMXBCKzBx
            TE9SVWxHVnBYSXVTZnlZVzV6dUJvY0EKE69vIH3jPK0me3eWsic5FqNvnQ2vCr5G
            16yQCitKJedbh9ce4lKeEfRnMqRejRC+Bp3PEOK3FpqHoze26DgUxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T16:34:14Z"
    mac: ENC[AES256_GCM,data:ydhD74dmH7XruXyBIM59h+Ady06PnyDgPBe8rcwWJ9iY8PlI8ozMGkFai+8L/biZ/ffuzNW1i/AcQqv2DuMTWAWk1CjmZ72kL3YwnQmJTbKHP40UXazS+LpuhhbkdEZU5uX35cX58db+G38usiptkj0aTk2VAAARyPJLGUwF3d4=,iv:bHb4eXswHhOhW2b7xDCOAYDbBuECcmsD6vCtlidb9PI=,tag:02JAJEzdRkFP2yVRiT5I7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
