argocdNamespace: sake-hack-ns
project: default

source:
  repoURL: https://github.com/sake-kasu/sake-hack-helm.git
  targetRevision: main

destination:
  server: https://kubernetes.default.svc
  namespace: sake-hack-ns

syncPolicy:
  automated:
    prune: false
    selfHeal: true
    allowEmpty: false
  syncOptions:
    - CreateNamespace=true

applications:
  - name: sake-hack-shared
    path: shared
    valueFiles:
      - values.yaml
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
    enabled: true
  - name: sake-hack-backend
    path: backend
    valueFiles:
      - values.yaml
    annotations:
      argocd.argoproj.io/sync-wave: "0"
    enabled: true
  - name: sake-hack-frontend
    path: frontend
    valueFiles:
      - values.yaml
    annotations:
      argocd.argoproj.io/sync-wave: "0"
    enabled: true
